### ISSUE TITLE
Moving items cause duplicates on update

### ISSUE THREAD

**Issue by Rarst** [WordPress/phpdoc-parser#145]
Example:
- https://developer.wordpress.org/reference/hooks/the_post/
- https://developer.wordpress.org/reference/hooks/the_post-2/

It seems like hook had been moved around in core source and update created duplicate, rather than update existing entry. This likely need to be better handled on updates.

**Comment by DrewAPicture** [comment]
#192 fixes the duplicate hooks being created issue only. If we want to look later and trash collecting the duplicates, we'll have to also look at merging all of the notes to the original and then simply updating the parent.
