### ISSUE TITLE
Question on Hook Post Content

### ISSUE THREAD

**Issue by bfintal** [WordPress/phpdoc-parser#161]
From what I understand, phpdoc-parser is used to generate https://developer.wordpress.org/reference/

I'm trying to use phpdoc-parser to document [Titan Framework](https://wordpress.org/plugins/titan-framework/) hooks. So far it has generated posts for hooks, but it's different than in the WP reference.

In WP reference, it has a description, the list of parameters, then a list of locations used. In what I generated, I only get the hook summary in an excerpt and the hook description as the content (overwriting anything in there), and the parameter list isn't there.

Is that the intended behavior?

**Comment by DrewAPicture** [comment]
The parameters are in post meta, under the `_wp_parser_args` key. And the locations used are generated with Posts 2 Posts.

**Comment by bfintal** [comment]
I see! It's `_wp-parser_args` and `_wp-parser-tags`
