### ISSUE TITLE
Fatal error: Class 'P2P_Storage' not found

### ISSUE THREAD

**Issue by hectorfarahani** [WordPress/phpdoc-parser#162]
Hi.
Using xampp on windows 10, activating wp parser plugin makes the below error:
Fatal error: Class 'P2P_Storage' not found in ...\wp-content\plugins\phpdoc-parserqer\lib\class-relationships.php on line 56

I dumped compeser autoload by 'composer dump-autoload' but error is still going.

**Comment by Rarst** [comment]
How precisely had you installed the plugin?

**Comment by hosein71** [comment]
installed using composer by git bash with this command : 

    composer create-project rmccue/wp-parser:dev-master --no-dev

**Comment by dd32** [comment]
I'm closing this issue due to it's age, and support nature.
