### ISSUE TITLE
Class 'WP_Widget' not found

### ISSUE THREAD

**Issue by parkerj** [WordPress/phpdoc-parser#166]
After updating to WordPress 4.4, I get the following error messages when trying to run the command __wp parser create__:

``` shell
Fatal error: Class 'WP_Widget' not found
```

**Comment by atimmer** [comment]
It looks like this is an issue fixed in a newer version of WP-CLI: https://github.com/wp-cli/wp-cli/issues/2284

**Comment by parkerj** [comment]
Thanks.
