### ISSUE TITLE
Should the parser handle front end output?

### ISSUE THREAD

**Issue by lkwdwrd** [WordPress/phpdoc-parser#168]
Right now there are template tags in the lib/template.php file. Devhub is not using any of these template tags at all. I propose that the parser itself stay out of display related helpers. This will allow the plugin to be focused completely on the data structures themselves rather than both parsing and display of data.

**Comment by lkwdwrd** [comment]
Some history in #14 and to some extent in #106 I just found. Generally agree with splitting this as described in #14.

**Comment by DrewAPicture** [comment]
I think it's best to keep the plugin focused on parsing and the data structures. Eventually I could see a companion plugin or base theme with templates, and yet another plugin with most of the helpers currently bundled in the wporg-developer theme.

**Comment by lkwdwrd** [comment]
In that case should we not pull out the template tags defined currently in the parser?
