### ISSUE TITLE
List child classes as "Used by" in the parent class

### ISSUE THREAD

**Issue by grappler** [WordPress/phpdoc-parser#179]
I was interested which classes extend the [`Walker`](https://developer.wordpress.org/reference/classes/walker/) class.

**Comment by DrewAPicture** [comment]
Interesting idea. This would be a great feature to implement on the Code Reference. The nice thing is that the parser already stores the parent classes in meta during parsing (`'extends`), so it would be a simple query to retrieve that list. Development for the Code Reference theme happens on meta trac so the best way to move forward with this would be to [create a ticket](https://meta.trac.wordpress.org/newtick) there. This repo is specifically for development of the parser :)

**Comment by grappler** [comment]
@DrewAPicture I love the robot who automatically created a meta ticket out of this issue. 😛

**Comment by DrewAPicture** [comment]
Yeah, I didn't ninja edit my reply fast enough haha.
