### ISSUE TITLE
Deprecated function using __FUNCTION__ processed incorectly.

### ISSUE THREAD

**Issue by grappler** [WordPress/phpdoc-parser#183]
Instead of not giving an alternative function, the version it is deprecated is being outputed.

![image](https://cloud.githubusercontent.com/assets/1785641/19295058/e39e0f16-906c-11e6-9c5d-17cf40fa5ce5.png)

The code for the deprecated function:

``` php
function wp_get_cookie_login() {
    _deprecated_function( __FUNCTION__, '2.5.0' );
    return false;
}
```

Reference to documentation
https://developer.wordpress.org/reference/functions/wp_get_cookie_login/

**Comment by coffee2code** [comment]
Hi @grappler, thanks for the report!

This was actually an issue with the theme for developer.wordpress.org and was filed (based off this ticket) on meta.trac at https://meta.trac.wordpress.org/ticket/2331.

The issue was fixed in https://meta.trac.wordpress.org/changeset/4556.

Cheers!
