### ISSUE TITLE
Only one dependency of wp_enqueue_script is displayed

### ISSUE THREAD

**Issue by grappler** [WordPress/phpdoc-parser#191]
I was studying the dependencies on the developer reference and realised that there were only single dependencies list instead of all of them. 

For example `jquery-masonry` has `jquery` and `masonry` as dependencies but only `jquery` is listed.

I am not sure if the tool does not filter for them or they are just not displayed.

https://developer.wordpress.org/reference/functions/wp_enqueue_script/

**Comment by JDGrimes** [comment]
Maybe I am missing something, but I don't know if this actually directly relates to the parser at all. I don't think the parser parses script dependencies, I always just assumed that list was manually curated. Maybe I'm wrong though.

**Comment by DrewAPicture** [comment]
The table on that page is manually curated. If there's an error on the reference article or you have suggestions for improvements, I suggest submitting a user contributed note at the bottom of the page.
