### ISSUE TITLE
proper place to ask questions on how to use this plugin?

### ISSUE THREAD

**Issue by pbiron** [WordPress/phpdoc-parser#193]
Where is the proper place to ask questions on how to use this plugin (as opposed to reporting bugs/enhancements)?   I've looked thru the open/closed issues here, it doesn't seem this is proper place.

I'm developing a documentation system for the plugins/themes that I write that is based on this plugin and a child of wporg-developer...and I have a few questions about using this plugin.

p.s. I have read [DevHub: Run WP-Parser](https://make.wordpress.org/docs/handbook/developer-resources/devhub/#6-run-wp-parser)

**Comment by DrewAPicture** [comment]
Hi @pbiron,

Probably the most immediate place to ask would be in the [#meta-devhub](https://wordpress.slack.com/messages/meta-devhub/) channel on the Making WordPress slack team. Hope that helps!

**Comment by pbiron** [comment]
yes it does.  I've solved the 2 probs that prompted me to open this issue...but if I have further probs I will raise them on #meta-devhub.
