### ISSUE TITLE
Is there a theme available to display the docs?

### ISSUE THREAD

**Issue by metamn** [WordPress/phpdoc-parser#202]
hello guys ... great job :smile: 

i've installed and run the plugin, the Functions/Methods/Classes/Hooks were generated.
now I should display them perhaps like on your site: https://developer.wordpress.org/reference/

i wonder if there is a theme to display the generated content.

if there is not then i'll have to create one. 
in this case if there are suggestions, needs, pain points etc. please let me know. they are all welcome.

**Comment by diddledan** [comment]
I've cobbled together a combination of Storefront (the WooCommerce theme) with bits borrowed from the DevHub svn: https://make.wordpress.org/docs/handbook/developer-resources/devhub/

It wasn't out of the box and required some work to get operational....

**Comment by DrewAPicture** [comment]
The theme used on wordpress.org can be found and checked out here with subversion: https://meta.svn.wordpress.org/sites/trunk/wordpress.org/public_html/wp-content/themes/pub/wporg-developer/
