### ISSUE TITLE
Error: 'parser' is not a registered wp command. On a multisite

### ISSUE THREAD

**Issue by sebastienserre** [WordPress/phpdoc-parser#218]
Hello,

I'm testing phpdoc-parser to make my own plugins doc but on a multisite I have the error:
"Error: 'parser' is not a registered wp command."
The plugin is activated on a subdomain

**Comment by pbiron** [comment]
Did you try using the `--url` arg?

`wp parser create --url=URL_OF_THE_SUBSITE`

**Comment by sebastienserre** [comment]
oh! many thanks Paul!
