### ISSUE TITLE
Excluding a folder from the parser

### ISSUE THREAD

**Issue by sebastienserre** [WordPress/phpdoc-parser#220]
Dear all,
Many thanks for sharing this project.
I'm starting to use it to create a WP plugin documentation and like to exclude from parsing, one or more folder.
Is a filter hook exists?

I've found `wp_parser_pre_import_file` but I prefered to remove a complete folder (and subfolder)

Many thanks for your help

**Comment by pbiron** [comment]
see #198

**Comment by sebastienserre** [comment]
great many thanks @pbiron
