### ISSUE TITLE
"wp plugin activate phpdoc-parser" returns "The 'wp-parser' plugin could not be found"

### ISSUE THREAD

**Issue by juanmaguitar** [WordPress/phpdoc-parser#226]
By following the [running](https://github.com/WordPress/phpdoc-parser#running) instructions, after having properly installed the plugin according the [installation instructions](https://github.com/WordPress/phpdoc-parser#requirements), I'm doing...

```
wp plugin activate phpdoc-parser
```

but I'm getting all the time the following error..

```
(base) ⬢  public  wp plugin activate wp-parser
Warning: The 'wp-parser' plugin could not be found.
Error: No plugins activated.
```

This error is not happening when I activate other plugins in the same plugins folder
```
(base) ⬢  public  wp plugin activate gutenberg
Warning: Plugin 'gutenberg' is already active.
Success: Plugin already activated.
```

This is the content of my plugins folder

```.
├── gutenberg
│   ├── README.md
│   ├── build
│   ├── changelog.txt
│   ├── gutenberg.php
│   ├── lib
│   ├── packages
│   ├── post-content.php
│   ├── readme.txt
│   └── vendor
├── index.php
├── phpdoc-parser
│   ├── README.md
│   ├── composer.json
│   ├── composer.lock
│   ├── lib
│   ├── phpunit.xml.dist
│   ├── plugin.php
│   ├── tests
│   └── vendor
```

**Comment by coffee2code** [comment]
Are you sure you are activating the `phpdoc-parser` plugin as the instructions indicate, or `wp-parser`?

> (base) ⬢  public  wp plugin activate wp-parser

Your CLI session snippet, and the error message you are reporting, suggest you used `wp-parser`, which isn't correct.

**Comment by juanmaguitar** [comment]
@coffee2code You're right! Thank you

The command `wp plugin activate phpdoc-parser` actually works from any folder inside the WordPress installation.
I was confused by the instructions at https://make.wordpress.org/docs/handbook/devhub/#4-install-wp-parser
