### ISSUE TITLE
Special Strings in the "new_admin_email_content" filter starting with ### not being parsed correctly

### ISSUE THREAD

**Issue by shawnhooper** [WordPress/phpdoc-parser#236]
_Originally posted in documentation GitHub https://github.com/WordPress/Documentation-Issue-Tracker/issues/1208_

## Issue Description

Special Strings in the "new_admin_email_content" filter documentation are incorrect.  They are missing the leading `###` characters. 

## URL of the Page with the Issue

https://developer.wordpress.org/reference/hooks/new_admin_email_content/

## Section of Page with the issue

Description 

## Why is this a problem?

Using the names specified in the documentation will result in the strings not being properly replaced when the new admin notification email is sent. 

## Suggested Fix

- `USERNAME###` should be changed to `###USERNAME###`
- `ADMIN_URL###` should be changed to `###ADMIN_URL###`
- `EMAIL###` should be changed to `###EMAIL###`
- `SITENAME###` should be changed to `###SITENAME###`
- `SITEURL###` should be changed to `###SITEURL###`

## How it appears in documentation 

![image](https://github.com/WordPress/phpdoc-parser/assets/2073284/ec3358fe-55f6-4379-9f8c-63669831dd61)

## How it appears in code 

![image](https://github.com/WordPress/phpdoc-parser/assets/2073284/fcf1022c-2d52-468a-8772-00b8ad0f8e7a)

**Comment by dd32** [comment]
This could be argued to be a core docs bug, as it's being parsed as markdown `###` being a h3.
Something like replacing it with a list, set of bullet points for each placeholder, such as is done with https://developer.wordpress.org/reference/hooks/site_admin_email_change_email/

I don't know why headers would be supported in PHPDoc though, so ideally we should be disabling that functionality.. but I'm not sure it's an "easy" change.

**Comment by dd32** [comment]
> I don't know why headers would be supported in PHPDoc though

This class makes a good reason why it exists:

https://developer.wordpress.org/reference/classes/wp_html_tag_processor/

This should be filed as a core docs bug.

**Comment by dd32** [comment]
Upstreamed this to here: https://core.trac.wordpress.org/ticket/60262#ticket
PR: https://github.com/WordPress/wordpress-develop/pull/5876
